FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

COPY zksync-web3-nova-* ./

ENV NODE_OPTIONS --max-old-space-size=4096

RUN apk add --no-cache --virtual .gyp \
        python3 \
        make \
        g++ \
        && npm install && apk del .gyp

COPY . .

CMD npm run migrate && npm run dev
