version: '3'

services:
  redis:
    restart: always
    image: redis:7-alpine
    env_file:
      - ./.env
    ports:
      - '6379:6379'

  db:
    image: postgres:16-alpine
    restart: always
    env_file:
      - ./.env
    ports:
      - '5432:5432'

  tapt:
    restart: always
    depends_on:
      - redis
      - db
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - ./.env
    ports:
      - '8080:8080/tcp'
    volumes:
      - .:/app
