name: Build & Release
on:
  push:
    branches: ['develop']

jobs:
  runTests:
    name: Run tests
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ['20']

    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install npm dependencies
        run: npm install

      - name: Run tests
        env:
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
        run: npm test
